# Generated by Django 4.2 on 2024-01-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_comment_app_comment_created_8d70f3_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='app_comment_created_8d70f3_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='app_comment_created_27a4e1_idx'),
        ),
    ]
