# Generated by Django 4.2 on 2024-01-26 06:31

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blog_tags'),
    ]

    operations = [
        TrigramExtension(),
    ]
